paths:
  scannet_path: /path/to/scannet # directory containing scene****_** subfolders
  synthetic_humans: /path/to/synthetic_humans # directory containing synthetic human meshes
  output_base_renders: /path/to/output_renders
  output_base_pcds: /path/to/output_pcds
  selected_bodies: data/selected_bodies_v3.json
  camera_parameters: data/camera_parameters.json
  faces_segmentation: data/smplx_faces_segmentation_unique.npy
  kinect_dot_pattern: data/kinect-pattern_3x3.png

camera:
  width: 640 # px
  height: 480 # px
  near_plane: 0.1 # m
  far_plane: 20. # m

rendering:
  samples_per_scene: 40
  valid_color_map_ids: [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    14,
    16,
    24,
    28,
    31,
    33,
    34,
    36,
    39,
    41,
  ]
  body_segments_order: [
    "rightHand",
    "rightUpLeg",
    "leftArm",
    "head",
    "leftEye",
    "rightEye",
    "leftLeg",
    "leftToeBase",
    "leftFoot",
    "spine1",
    "spine2",
    "leftShoulder",
    "rightShoulder",
    "rightFoot",
    "rightArm",
    "leftHandIndex1",
    "rightLeg",
    "rightHandIndex1",
    "leftForeArm",
    "rightForeArm",
    "neck",
    "rightToeBase",
    "spine",
    "leftUpLeg",
    "leftHand",
    "hips"
    ]
  color_map:
    -1: [255., 255., 255.]
    0: [0., 0., 0.]
    1: [174., 199., 232.]
    2: [152., 223., 138.]
    3: [31., 119., 180.]
    4: [255., 187., 120.]
    5: [188., 189., 34.]
    6: [140., 86., 75.]
    7: [255., 152., 150.]
    8: [214., 39., 40.]
    9: [197., 176., 213.]
    10: [148., 103., 189.]
    11: [196., 156., 148.]
    12: [23., 190., 207.]
    14: [247., 182., 210.]
    15: [66., 188., 102.]
    16: [219., 219., 141.]
    17: [140., 57., 197.]
    18: [202., 185., 52.]
    19: [51., 176., 203.]
    20: [200., 54., 131.]
    21: [92., 193., 61.]
    22: [78., 71., 183.]
    23: [172., 114., 82.]
    24: [255., 127., 14.]
    25: [91., 163., 138.]
    26: [153., 98., 156.]
    27: [140., 153., 101.]
    28: [158., 218., 229.]
    29: [100., 125., 154.]
    30: [178., 127., 135.]
    31: [120., 185., 128.]
    32: [146., 111., 194.]
    33: [44., 160., 44.]
    34: [112., 128., 144.]
    35: [96., 207., 209.]
    36: [227., 119., 194.]
    37: [213., 92., 176.]
    38: [94., 106., 211.]
    39: [82., 84., 163.]
    40: [100., 85., 144.]
    41: [0., 0., 255.] #artificial human
    # body parts
    100: [35., 69., 100.] # rightHand
    101: [73., 196., 37.] # rightUpLeg
    102: [121., 25., 252.] # leftArm
    103: [96., 237., 31.] # head
    104: [55., 40., 93.] # leftEye
    105: [75., 180., 125.] # rightEye
    106: [165., 38., 65.] # leftLeg
    107: [63., 75., 77.] # leftToeBase
    108: [27., 255., 80.] # leftFoot
    109: [82., 110., 90.] # spine1
    110: [87., 54., 10.] # spine2
    111: [210., 200., 110.] # leftShoulder
    112: [217., 212., 76.] # rightShoulder
    113: [254., 176., 234.] # rightFoot
    114: [111., 140., 56.] # rightArm
    115: [83., 15., 157.] # leftHandIndex1
    116: [98., 255., 160.] # rightLeg
    117: [153., 170., 17.] # rightHandIndex1
    118: [54., 82., 122.] # leftForeArm
    119: [10., 19., 94.] # rightForeArm
    120: [1., 147., 72.] # neck
    121: [47., 210., 21.] # rightToeBase
    122: [174., 22., 133.] # spine
    123: [98., 58., 83.] # leftUpLeg
    124: [222., 25., 45.] # leftHand
    125: [75., 233., 65.] # hips


  pcd_computation:
    add_kinect_noise: True
    verbose: True